### PR TITLE
fix: change the id type from product

### LINKED ISSUE #61: Product Management - fix product id (front)

### PR DESCRIPTION
**Pull request by MeloLawson**
change the type from int to string (no real UUID type in flutter, only a generator)

closed #61

### CODE REVIEW

File: terminal/test/feature/product/presentation/products_bloc_test.dart [hunk 1]
```diff
@@ -19,9 +19,9 @@ void main() {
     EquatableConfig.stringify = true;
     getAllProducts = MockGetAllProducts();
     productsBloc = ProductsBloc(getAllProducts: getAllProducts);
-    products= [const Product(id :1,name :"poivrons",price : 5.0, stock :100),
-      const Product(id :1,name :"salades",price : 5.0, stock :100),
-      const Product(id :1,name :"oignons",price : 5.0, stock :100)
+    products= [const Product(id : "4c589f34-12a6-4075-a1ea-ad3b9009c8e1",name :"poivrons",price : 5.0, stock :100),
```
Comment (PaulIRVOAS) [inline terminal/test/feature/product/presentation/products_bloc_test.dart:22]: To expensive price for a "poivron" but OK, PR accepted  :)

**Review by PaulIRVOAS — APPROVED** [review]
OK
